159 refactor profile front
Pixailz/ft_transcendence pull request #160
Opened 2023-09-22 07:47 UTC by Ycaro02

2023-09-22 11:26 UTC, Pixailz approved these changes
Good job, working great and the nickname spin well :p

2023-09-26 12:13 UTC, Pixailz approved these changes
noice, working great :)

2023-09-27 16:12 UTC, Pixailz commented on docker-compose-dev.yaml
> -      interval: 5s
Why ?

this change a lot on the CI side, 5min is good enought to deploy the whole project

2023-09-27 16:15 UTC, Pixailz requested changes
Some change have to be done according to comment

2023-09-28 08:14 UTC, RuBeeN-cmd approved these changes
Nice work

2023-09-28 08:17 UTC, RuBeeN-cmd approved these changes
Resolved

2023-09-29 09:26 UTC, Pixailz approved these changes
Noice :heart:

2023-09-29 09:33 UTC, Pixailz commented
don't forget to squash before merging, noice improvement on the artistic side :D

2023-09-29 09:56 UTC, merged