(#184) create new message content table
Pixailz/ft_transcendence pull request #187
Opened 2023-10-12 15:08 UTC by Pixailz

concerning only the chat dm because chat channel has refactor in progress

- [x] player can send string or game-invite type
- [ ] player can send string and game-invite type

2023-10-12 16:04 UTC, Pixailz commented
can now send string and game-invite at the same time

![image](https://github.com/Pixailz/ft_transcendence/assets/35565530/bf758d7c-624f-4db2-aa4e-27e0ccb0067f)

to do so:
1. Write a string
2. Click on the '+' button
3. Click on GameInvite
4. Write the room id (or something else)
5. send it

the form is reseted after sending a message

2023-10-13 05:25 UTC, Pixailz commented
- fix several jerk code that was causing a lot of trouble
- merge create custom game with the lobby
![image](https://github.com/Pixailz/ft_transcendence/assets/35565530/66024ea6-b52b-4949-868e-47b92bbb4f6b)
- send notifications and message on game invite
  - integrate a button into the chat to join a game, with a default string
![image](https://github.com/Pixailz/ft_transcendence/assets/35565530/cb99b5a0-b751-469c-8e70-71b148242653)
- make chad private game proof against the matchmaking

2023-10-16 14:04 UTC, Pixailz commented
need to be tested, but ready to PR :)

2023-10-16 22:41 UTC, clinche requested changes
nestjs wont launch due to duplicates and angular fails with a lot of errors, the first being
```
Error: src/app/app.component.html:1:1 - error NG8001: 'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

2023-10-16 22:41 UTC, clinche commented on src/nestjs/src/modules/database/database.module.ts
> +import { DBMessageContentService } from "./messageContent/service";
duplicate of lines 38-39

2023-10-16 22:42 UTC, Pixailz commented
fixed :)

2023-10-16 22:57 UTC, clinche approved these changes
looks noice to me

2023-10-16 23:09 UTC, merged